In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
my_arr = np.arange(10)
print(my_arr)
print(type(my_arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [3]:
my_list = list(range(10))
print(my_list)
print(type(my_list))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [5]:
import numpy as np
import sys
S= range(1000)
print("Size of each element of list in bytes: ",sys.getsizeof(S))
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))
D= np.arange(1000)
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


In [6]:
print(type(S))

<class 'range'>


In [67]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)
print(arr5.dtype)

float64
float64
float64
int64
float64


In [70]:
arr5=np.array([1, 2, 3, 4, 5])
arr6=np.array([[1, 2, 3], [4, 5, 6]])
arr7=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr5)
print(arr6)
print(arr7)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [8]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print("Shape= ",data.shape)
print("Type= ",data.dtype)
print("Data = ", data)
print("\nAns1 = ",data * 10)
print("\nAns2= ",data+data)

Shape=  (2, 3)
Type=  float64
Data =  [[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]

Ans1 =  [[ 15.  -1.  30.]
 [  0. -30.  65.]]

Ans2=  [[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]


In [9]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(type(arr))
print(arr)
print("\n", arr.dtype)

<class 'numpy.ndarray'>
[1 2 3 4 5]

 int64


In [66]:
arr1=np.zeros(6)
print(arr1)
arr2=np.ones(6)
print(arr2)
arr3=np.empty(3)
print(arr3)
arr4=np.array([1,2,3,4,5])
print(arr4)
arr5=np.eye(3)
print(arr5)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1.]
[1 2 3 4 5]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype='d')
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [11]:
arr = np.array([1, 2, 3])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('f')
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  [1 2 3] int64
After converting:  [1. 2. 3.] float32


In [12]:
arr = np.array([1.1, 2.2, 3.3])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('i')
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  [1.1 2.2 3.3] float64
After converting:  [1 2 3] int32


In [13]:
arr = np.array(['1.1', '2.2', '-3.3'])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('f')
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  ['1.1' '2.2' '-3.3'] <U4
After converting:  [ 1.1  2.2 -3.3] float32


In [16]:
arr = np.array(['1.1', '2.2', 'abc'])
print("Before converting: ", arr, arr.dtype)
try:
    new_arr = arr.astype('f')
    print("After converting: ", new_arr, new_arr.dtype)
except ValueError as e:
    print("Conversion failed:", e)

Before converting:  ['1.1' '2.2' 'abc'] <U3
Conversion failed: could not convert string to float: np.str_('abc')


In [17]:
arr1 = np.arange(10)
arr2 = np.random.randn(10)
print("array 1\n",arr1, arr1.dtype)
print("Array 2 \n",arr2, arr2.dtype)
new_arr = arr1.astype(arr2.dtype)
print("New Array \n",new_arr, new_arr.dtype)

array 1
 [0 1 2 3 4 5 6 7 8 9] int64
Array 2 
 [-0.85096258 -1.30802743 -0.63434512 -1.19566048  0.75698268 -0.96427669
  0.39860475  0.33730931  1.48156742 -2.25557825] float64
New Array 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [20]:
str_arr = np.array(['hello', 'world', 'numpy'])
print(str_arr)

['hello' 'world' 'numpy']


In [22]:
import numpy as np
a = np.array([1., 2., 3., 4.])
b = np.array([5., 6., 7., 8.])
print(a + b) 
print(a - b) 
print(a * b) 
print(a / b) 
print(a ** b)

[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [25]:
a=np.array([1.,2.,3.,4.])
print(a+1)
print(a-1)
print(a*2)
print(a/2)
print(a**2)
print(1/a)

[2. 3. 4. 5.]
[0. 1. 2. 3.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]
[ 1.  4.  9. 16.]
[1.         0.5        0.33333333 0.25      ]


In [32]:
arr = np.arange(12)
newarr = arr.reshape(4, 3)
print(newarr)
newarr = arr.reshape((4, 3),order='F')
print("\n",newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [34]:
arr = np.array([[1, 2, 3, 4, 9, 10], [5, 6, 7, 8, 11, 12]])
print(arr)
newarr = arr.reshape(3, 2, 2)
print("\n",newarr)
newarr1 = newarr.reshape(3, -1)
print("\n reshape(3,-1) \n",newarr1)

[[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]

 [[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [ 5  6]]

 [[ 7  8]
  [11 12]]]

 reshape(3,-1) 
 [[ 1  2  3  4]
 [ 9 10  5  6]
 [ 7  8 11 12]]


In [35]:
original_array = np.array([[10, 20], [30, 40]])
print("Original array:\n", original_array)

flattened_array = original_array.flatten()
flattened_array[0] = 999
print("Flattened array:\n", flattened_array)

raveled_array = original_array.ravel()
raveled_array[1] = 888
print("Original array:\n", original_array)

print("Raveled array:\n", raveled_array)
print("Original array:\n", original_array)

Original array:
 [[10 20]
 [30 40]]
Flattened array:
 [999  20  30  40]
Original array:
 [[ 10 888]
 [ 30  40]]
Raveled array:
 [ 10 888  30  40]
Original array:
 [[ 10 888]
 [ 30  40]]


In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
r_arr = np.ravel(arr)
print("Flattened array:", r_arr)
r_arr[0] = 10
print("Original array after modification:", arr)

Flattened array: [1 2 3 4 5 6]
Original array after modification: [[10  2  3]
 [ 4  5  6]]


In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
f_arr = arr.flatten()
print("Flattened array:", f_arr)
f_arr[0] = 10
print("original array after flattening:", arr)

Flattened array: [1 2 3 4 5 6]
original array after flattening: [[1 2 3]
 [4 5 6]]


In [38]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 1], [3, 5]])

greater_than = arr1 > arr2
less_than = arr1 < arr2
equal_to = arr1 == arr2
print("Greater than:\n", greater_than)
print("\nLess than:\n", less_than)
print("\nEqual to:\n", equal_to)

arr3 = np.array([1, 2, 3])
arr4 = np.array([1, 2, 3])
arr5 = np.array([1, 2, 4])
result1 = np.array_equal(arr3, arr4)
result2 = np.array_equal(arr3, arr5)
print("\nArray-wise comparison 1:", result1)
print("Array-wise comparison 2:", result2)

Greater than:
 [[False  True]
 [False False]]

Less than:
 [[ True False]
 [False  True]]

Equal to:
 [[False False]
 [ True False]]

Array-wise comparison 1: True
Array-wise comparison 2: False


In [45]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [46]:
other_arr = np.ones((3, 5))
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
import numpy as np
x = np.arange(10)
print("x= ",x)
print("\n x[:5]= ",x[:5])
print("\n x[5:]= ",x[5:])
print("\n x[4:7]= ",x[4:7])
print("\n x[::2]= ",x[::2])
print("\n x[1::2]= ",x[1::2])
print("\n x[::-1]= ",x[::-1])
print("\n x[5::-2]= ",x[5::-2])

x=  [0 1 2 3 4 5 6 7 8 9]

 x[:5]=  [0 1 2 3 4]

 x[5:]=  [5 6 7 8 9]

 x[4:7]=  [4 5 6]

 x[::2]=  [0 2 4 6 8]

 x[1::2]=  [1 3 5 7 9]

 x[::-1]=  [9 8 7 6 5 4 3 2 1 0]

 x[5::-2]=  [5 3 1]


In [48]:
x = np.arange(10)
print(x)
x[5:] = 2
print("\n After broadcasting1",x)
x[::2] = 100
print("\n After broadcasting2",x)

[0 1 2 3 4 5 6 7 8 9]

 After broadcasting1 [0 1 2 3 4 2 2 2 2 2]

 After broadcasting2 [100   1 100   3 100   2 100   2 100   2]


In [51]:
x = np.arange(10)
print("Original array:", x)
view = x[2:7]
print("View of the array:", view)
view[1:4] = 99
print("Modified view:", view)
print("Original array after modifying the view:", x)
view[:] = -9
print("Modified view:", view)
print("Original array after modifying the view:", x)
x_copy = x[2:7].copy()
x_copy[:] = 100
print("Modified copy:", x_copy)
print("Original array:", x)

Original array: [0 1 2 3 4 5 6 7 8 9]
View of the array: [2 3 4 5 6]
Modified view: [ 2 99 99 99  6]
Original array after modifying the view: [ 0  1  2 99 99 99  6  7  8  9]
Modified view: [-9 -9 -9 -9 -9]
Original array after modifying the view: [ 0  1 -9 -9 -9 -9 -9  7  8  9]
Modified copy: [100 100 100 100 100]
Original array: [ 0  1 -9 -9 -9 -9 -9  7  8  9]


In [52]:
x2 = np.array([[12, 5, 2, 4],[ 7, 6, 8, 8],[ 1, 6, 7, 7]])
print(x2[2,0])
print(x2[1][2])
print(x2[2,-1])
print(x2[0])

1
8
7
[12  5  2  4]


In [55]:
import numpy as np

x3 = np.array([
    [[12, 5, 2, 4],
     [ 7, 6, 8, 8]],
    [[ 1, 6, 7, 7],
     [ 3, 4, 5, 9]]
])

print(x3[0])
print(x3[1, 0, 2])
print(x3[0][1][2])
print(x3[1, -1, -1])

[[12  5  2  4]
 [ 7  6  8  8]]
7
8
9


In [56]:
x2_old = x2.copy()
x2[0] = 99
print("\n x2 = \n", x2)

x3_old = x3[1].copy()
x3[1] = 99
print("\n x3 = \n", x3)

x3[1] = x3_old
print("\n x3 = \n", x3)


 x2 = 
 [[99 99 99 99]
 [ 7  6  8  8]
 [ 1  6  7  7]]

 x3 = 
 [[[12  5  2  4]
  [ 7  6  8  8]]

 [[99 99 99 99]
  [99 99 99 99]]]

 x3 = 
 [[[12  5  2  4]
  [ 7  6  8  8]]

 [[ 1  6  7  7]
  [ 3  4  5  9]]]


In [58]:
x2 = np.array([[12, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
print("x2= ",x2)
print("\n x2[:2, :3] = \n",x2[:2, :3])
print("\n x2[:3, ::2]=\n ",x2[:3, ::2])
print("\n x2[::-1,::-1]= \n",x2[::-1, ::-1])
print("\n x2[::-1]= \n",x2[::-1])

x2=  [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

 x2[:2, :3] = 
 [[12  5  2]
 [ 7  6  8]]

 x2[:3, ::2]=
  [[12  2]
 [ 7  8]
 [ 1  7]]

 x2[::-1,::-1]= 
 [[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]

 x2[::-1]= 
 [[ 1  6  7  7]
 [ 7  6  8  8]
 [12  5  2  4]]


In [59]:
import numpy as np
x=np.arange(24).reshape(2,3,4)
print(x)
print(x[:,0])
print(x[:,:,0])
print(x[...,0])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [12 13 14 15]]
[[ 0  4  8]
 [12 16 20]]
[[ 0  4  8]
 [12 16 20]]


In [60]:
print("x2= \n",x2)
print("x2[:2, ::2]= \n",x2[:2, ::2])
print("x2[1, :2]= \n",x2[1, :2])

x2= 
 [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
x2[:2, ::2]= 
 [[12  2]
 [ 7  8]]
x2[1, :2]= 
 [7 6]


In [61]:
a=np.arange(12).reshape(3,4)
print("a= \n",a)
b=a>4
print("b= \n",b)
print("a[b]= \n",a[b]) # 1d array
a[b] = 1
print("a= \n",a)

a= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b= 
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
a[b]= 
 [ 5  6  7  8  9 10 11]
a= 
 [[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [58]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.arange(28).reshape(7,4)
print(names)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


In [59]:
print("data= \n",data)

data= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [60]:
print("names bool= \n",names=='Bob')

names bool= 
 [ True False False  True False False False]


In [61]:
print("names == 'Bob' \n",data[names == 'Bob'])

names == 'Bob' 
 [[ 0  1  2  3]
 [12 13 14 15]]


In [62]:
print("names == 'Bob',2: \n",data[names == 'Bob', 2:])

names == 'Bob',2: 
 [[ 2  3]
 [14 15]]


In [63]:
print("names == 'Bob',3: \n",data[names == 'Bob', 3])

names == 'Bob',3: 
 [ 3 15]


In [62]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(28).reshape(7, 4)
print(data[names != 'Bob'])
print("\n",data[~(names == 'Bob')])
data[names != 'Bob']=-1
print("\ndata= \n",data)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]

 [[ 4  5  6  7]
 [ 8  9 10 11]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]

data= 
 [[ 0  1  2  3]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [12 13 14 15]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [63]:
import numpy as np

names = np.array(['Alice', 'Bob', 'Charlie', 'David'])
ages = np.array([25.5, 30, 28.2, 35])

older_than_29 = ages > 29
print("People older than 29:", names[older_than_29])

names_to_select = (names == 'Alice') | (names == 'Charlie')
print("Ages of Alice and Charlie:", ages[names_to_select])

People older than 29: ['Bob' 'David']
Ages of Alice and Charlie: [25.5 28.2]


In [64]:
import numpy as np

city_names = np.array(['New York', 'Los Angeles', 'Chicago', 'Houston'])
temperatures = np.array([25, 32, 28, 35])

hot_threshold = 30
hot_cities_bool = temperatures > hot_threshold
hot_cities = city_names[hot_cities_bool]
print("Hot cities:", hot_cities)

Hot cities: ['Los Angeles' 'Houston']


In [66]:
city_names = np.array(['New York', 'Los Angeles', 'Chicago', 'Houston'])
temperatures = np.array([-25, 32, -28, 35])
negative_temp_indices = temperatures < 0 
temperatures[negative_temp_indices] = 0
print("Updated temperatures:", temperatures)

Updated temperatures: [ 0 32  0 35]


In [67]:
arr = np.arange(32).reshape(8, 4)
print("arr= \n", arr)

print("\narr[[1, 5, 7, 2]]= \n", arr[[1, 5, 7, 2]])

print("\narr[[1, 5, 7, 2], [0, 3, 1, 2]]= \n", arr[[1, 5, 7, 2], [0, 3, 1, 2]])

print("\narr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]= \n", arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

print("\narr[[-3, -5, -7]]= \n", arr[[-3, -5, -7]])
arr[[1, 5, 7, 2]] = 1
print("\narr= \n", arr)

arr= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

arr[[1, 5, 7, 2]]= 
 [[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

arr[[1, 5, 7, 2], [0, 3, 1, 2]]= 
 [ 4 23 29 10]

arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]= 
 [[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]

arr[[-3, -5, -7]]= 
 [[20 21 22 23]
 [12 13 14 15]
 [ 4  5  6  7]]

arr= 
 [[ 0  1  2  3]
 [ 1  1  1  1]
 [ 1  1  1  1]
 [12 13 14 15]
 [16 17 18 19]
 [ 1  1  1  1]
 [24 25 26 27]
 [ 1  1  1  1]]


In [68]:
import numpy as np
arr = np.arange(12).reshape((3, 4))
print(arr)
print("Transpose using .T")
print(arr.T)
print("Transpose using the transpose() function")
print(np.transpose(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose using .T
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Transpose using the transpose() function
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [69]:
arr1=np.transpose(arr,(1,0))
print(arr1)
arr2=np.transpose(arr,(0,1))
print(arr2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [71]:
arr = np.arange(12).reshape((2, 3,2))
print(arr)
print("Transpose using .T")
arr3dT=arr.T
print(arr3dT)
print(arr3dT.shape)
print("Transpose using the transpose() function")
print(np.transpose(arr))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Transpose using .T
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
(2, 3, 2)
Transpose using the transpose() function
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [72]:
arr3d1=np.transpose(arr,(1,0,2))
print(arr3d1)
arr3d2=np.transpose(arr,(0,1,2))
print(arr3d2)

[[[ 0  1]
  [ 6  7]]

 [[ 2  3]
  [ 8  9]]

 [[ 4  5]
  [10 11]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [73]:
import numpy as np
arr = np.arange(12).reshape((3, 4))
print("Dot product of arr and arr2:")
print(np.dot(arr, arr.T))

Dot product of arr and arr2:
[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


In [74]:
import numpy as np
arr = np.arange(12).reshape((3, 4))
print(arr)
print("Swap axes 0 and 1:")
print(np.swapaxes(arr, 0, 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swap axes 0 and 1:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [75]:
import numpy as np
arr1 = np.array([[1, 2],
[3, 4]])
arr2 = np.array([[5, 6],
[7, 8]])
result = np.multiply(arr1, arr2)
print("Result of element-wise multiplication:")
print(result)

Result of element-wise multiplication:
[[ 5 12]
 [21 32]]


In [76]:
result = np.matmul(arr1, arr2)
print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
[[19 22]
 [43 50]]


In [77]:
result = np.dot(arr1, arr2)
print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
[[19 22]
 [43 50]]
